version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build-and-deploy:
    docker:
      - image: cimg/node:18.17.1
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Build Application
          command: NODE_OPTIONS=--openssl-legacy-provider yarn build
      - run:
          name: Install FTP Client
          command: |
            sudo apt-get update
            sudo apt-get install -y lftp
      - run:
          name: Deploy to FTP
          command: |
            lftp -u $FTP_USER,$FTP_PASSWORD $FTP_HOST \<<EOF
            cd /public_html
            rm -rf *
            mirror -R ./build/ ./
            quit
            EOF
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only: master