name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.1
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build application
        run: NODE_OPTIONS=--openssl-legacy-provider yarn build

      - name: Install FTP client (lftp)
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp

      - name: Deploy to FTP
        env:
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_HOST: ${{ secrets.FTP_HOST }}
        run: |
          lftp -u $FTP_USER,$FTP_PASSWORD $FTP_HOST <<EOF
          cd /public_html
          rm -rf *
          mirror -R ./build/ ./
          quit
          EOF
